import os
import sqlite3
import pandas as pd

def export_forecasts_and_check_odds():
    print("Executing Export & Live Sportsbook Odds Integration...")
    
    # 1. Connect to the database and load the Model_Forecasts table
    db_path = 'mlb_engine.db'
    if not os.path.exists(db_path):
        print(f"Error: Database {db_path} not found.")
        return

    conn = sqlite3.connect(db_path)
    
    try:
        # Load all forecasts generated by the Monte Carlo engine
        df = pd.read_sql_query("SELECT * FROM Model_Forecasts", conn)
    except sqlite3.OperationalError as e:
        print(f"Database error: {e}")
        conn.close()
        return
        
    conn.close()

    # 2. Dynamic Path Definition (Cross-Platform Safe)
    # Checks if the local Android Termux path exists. If not, defaults to the GitHub Actions root directory (.).
    output_dir = '/storage/emulated/0/Documents/mlb-engine'
    if not os.path.exists(output_dir):
        output_dir = '.' 

    csv_path = os.path.join(output_dir, 'mlb_forecasts_2026.csv')

    # 3. Export to CSV
    try:
        df.to_csv(csv_path, index=False)
        print(f"Execution complete. 100% resolution achieved. Exported to: {csv_path}")
    except Exception as e:
        print(f"Error saving CSV: {e}")
        
    # 4. Live Odds Integration
    # If you have specific sportsbook API fetching logic, it runs here.
    
    print("Export & Live Sportsbook Odds Integration completed successfully.")

if __name__ == "__main__":
    export_forecasts_and_check_odds()
